on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: ohua29@gmail.com
        MAX_DAYS: 1000
        MIN_COMMITS_PER_DAY: 0
        MAX_COMMITS_PER_DAY: 35
        INCLUDE_WEEKENDS: false
